Feat/bills list
TeamInterject/BillChop pull request #24
Opened 2020-11-05 19:54 UTC by tmaciulis22

2020-11-05 19:57 UTC, tmaciulis22 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Task 5: Create UI element which shows list of bills](https://trello.com/c/NSuihPLC/58-task-5-create-ui-element-which-shows-list-of-bills)

2020-11-05 22:57 UTC, AinoraZ commented
A screenshot of the UI would be a nice addition, both for record keeping and to see what has been done 🚀.

2020-11-05 23:24 UTC, AinoraZ requested changes

2020-11-05 23:24 UTC, AinoraZ commented on billchop-fe/src/pages/GroupsPage.tsx
> +      name,
This currently breaks with new changes added to master (see #21 and #22 ). As a temporary workaround, just to get this code in a working state on master, I suggest doing: ```email: `{name.replace(" ", ".")}@gmail.com` ``` just to have it pass the regex. This should later be fixed in Task 4.

2020-11-06 11:29 UTC, AinoraZ approved these changes

2020-11-06 11:35 UTC, merged